export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const REMOVE__FROM__CART = 'REMOVE__FROM__CART';
export const SHIPPING_DETAILS = 'SHIPPING_DETAILS';
export const PAYMENT_METHOD = 'PAYMENT_METHOD';
export const EMPTY_CART = 'EMPTY_CART';